baseURL: "/"
title: Christopher Li
paginate: 5
theme: PaperMod
languageCode: "en-us"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Chris
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/CL.png"
    favicon16x16: "/images/CL.png"
    favicon32x32: "/images/CL.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Christopher Li"
    Content: |
      \
      Hey! I'm Chris :) \
      \
      I call Cupertino, California home, but I am currently studying **CS** at [**New York University**](https://www.nyu.edu/) (CAS '26). \
      \
      In my free time, I like **reading** (working through *Upshift* by Ben Ramalingam right now), **sports** (especially soccer, basketball, and F1)
      and **cafes** (always on the lookout for hidden NYC gems!)
      \
      \
      Here are some side quests I'm working on or have pursued in the past: 
      - **Incoming Software Engineer Intern** (Summer 2025)
      - **Head Teaching Assistant** -- NYU CSCI-UA 101 (Fall 2023, 2024, 2025)
      - [**VimCat**](https://devpost.com/software/vimcat) -- Game aimed at faciliating Vim learning; 1st place at HackNYU (Winter 2023)
      - **Software Engineer Intern at [Pulsar](https://www.linkedin.com/company/pulsar-is/)** -- Scraped data from over 250,000 companies; built a ReactJS/NodeJS/MySQL dashboard (Fall 2023)
      - [**TL;DR**](https://chromewebstore.google.com/detail/tldr-gpt3-news-summarizer/ddikohmknplkcapomompgabjabbicaij) (Discontinued) -- Chrome extension that generates paragraph-length summaries and translates news articles, using the OpenAI API (Spring 2023)

      \
      Feel free to get in touch! christopherli@nyu.edu


      

      
      


  socialIcons:
    - name: email
      url: "mailto:christopherli@nyu.edu"
    - name: linkedin
      url: "https://www.linkedin.com/in/christopherrli/"
    - name: github
      url: "https://github.com/christopherlii"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #originally in, but dont want people to edit my posts right now 
  #editPost:
    #URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
